#!/bin/bash
. /usr/local/bin/bargus_functions.sh

PREFIX=bargus_
LOC=S5

#2013.12.16
#YY=2013
#mm=12
#dd=16
#HHMM=19.00

YY=`date +%Y`
mm=`date +%m`
dd=`date +%d`
HH=`date +%H`
#MM=`date +%M`
HHMM=$HH

#YY=2014
#mm=02
#dates="1 10"
#dd='03'
#HH='01'
#YY=2013
#mm=12
#dates="1 31"

#for dd in `seq -w $dates`; do
#  for HH in `seq -w 0 23`; do
    HHMM=$HH

PATH=/usr/local/bin:$PATH

#/var/log/argus/archive/2013/12/15
ARCHIVE=/var/log/argus/archive
DIRIN=$ARCHIVE/$YY/$mm/$dd
INPF=$DIRIN/argus.$YY.$mm.$dd.$HHMM*.gz

if [ ! -e $INPF ]; then
  echo Input file $INPF not found, continuing...
  continue
fi

echo processing $INPF
bname=`basename $INPF .gz`

STATS=/var/log/argus/stats
DIROUT=$STATS/$YY/$mm/$dd
BYTESF=$DIROUT/bytes.$bname.csv
AVGRATESF=$DIROUT/avgrates.$bname.csv
TS=$bname

if [ ! -d $DIROUT ]; then
  mkdir -p $DIROUT
fi


compute_bytes_log
compute_bitrate_log

#  done
#done
