#!/bin/bash
. /usr/local/bin/cargus_functions.sh

N_ARGS=4
PREFIX=cargus_
LOC=S4

if [ $# -ne "$N_ARGS" ]
then
    YY=`date +%Y`
    MM=`date +%m`
    DD=`date +%d`
    HH=`date +%H`
else
    YY=$1
    MM=$2
    DD=$3
    HH=$4
fi

PATH=/usr/local/bin:$PATH


##### for cargus
ARCHIVE=/var/log/cargus/archive
STATS=/var/log/cargus/stats
DIRIN=$ARCHIVE/$YY/$MM/$DD
if [ ! -d $DIRIN ]; then
  mkdir -p $DIRIN
fi

##### for cargus
echo "yiannis-1"
INPF=$DIRIN/argus.$YY.$MM.$DD.$HH
echo $INPF
echo "yiannis-2"

echo processing $INPF
bname=`basename $INPF .gz`
echo basename=$bname

DIROUT=$STATS/$YY/$MM/$DD
BYTESF=$DIROUT/bytes.$bname.csv
AVGRATESF=$DIROUT/avgrates.$bname.csv
TS="malakas.$YY.$MM.$DD.$HH.59.00"

if [ ! -d $DIROUT ]; then
  mkdir -p $DIROUT
fi

compute_bytes_log
#compute_bitrate_log

#  done
#done
